name: env_zoo_calrissian
channels:
  - terradue
  - conda-forge
  - eoepca
dependencies:
  - black
  - pre-commit
  - isort
  - flake8
  - autoflake
  - pylint
  - nose2
  - cwl-wrapper >= 0.10.0
  - pycalrissian >= 0.4.0
  - pip
  - pip:
    - kubernetes
    - pdocs
    - cwl-utils
  - loguru
