name: env_zoo_calrissian
channels:
  - terradue
  - conda-forge
  - eoepca
dependencies:
  - black
  - pre-commit
  - isort
  - flake8
  - autoflake
  - pylint
  - nose2
  - pycalrissian >= 0.6.0
  - cwl-wrapper >= 0.11.7
  - pip
  - pip:
    - kubernetes
    - pdocs
    - cwl-utils==0.12
    - attrs
    - python-dotenv
  - loguru
