name: docs
on:
  push:
    branches:
      - develop
      - main
    paths:
      # Only rebuild website when docs have changed
      - 'README.md'
      - 'docs/**'
      - 'mkdocs.yml'
      - .github/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@main

      - name: Install dependencies
        run: |
          micromamba create -f .devcontainer/environment.yml
          pip install mkdocs-material mkdocs-jupyter
          python setup.py install
      - name: update API docs
        run: |
          pdocs as_markdown --output_dir docs/api/ --exclude_source --overwrite zoo-calrissian-runner

      - run: mkdocs gh-deploy --force
